import { AgentService } from "./agentService"

export class OllamaAgentService implements AgentService {

  private model: string

  constructor(model: string = "llama3") {
    this.model = model
  }

  private async generate(
    prompt: string
  ): Promise<string> {

    const response = await fetch(
      "http://localhost:11434/api/generate",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          model: this.model,
          prompt,
          stream: false
        })
      }
    )

    if (!response.ok) {
      throw new Error("Ollama request failed")
    }

    const data = await response.json()

    return data.response
  }

  // -----------------------------
  // STEP 1 — PLANNER + SELECTOR
  // -----------------------------

  async planAndSelect(
  query: string
): Promise<{
  planText: string
  selector: {
    focus: string
    rationale: string
  }
}> {

  const prompt = `
Create a structured research plan for:

${query}

Return:

1) Plan
2) Focus
3) Rationale
`

  const text = await this.generate(prompt)

  return {
    planText: text,
    selector: {
      focus: "General",
      rationale: "Generated by Ollama"
    }
  }

}
  // -----------------------------
  // STEP 2 — REPORTER + REVIEWER
  // -----------------------------

  async reportAndReview(
    query: string,
    context: string,
    perspective: any
  ): Promise<{
    draft: string
    review: string
  }> {

    const prompt = `
Perspective:
${JSON.stringify(perspective)}

Query:
${query}

Context:
${context}

Write:

1) Draft report
2) Review of accuracy
`

    const text = await this.generate(prompt)

    return {
      draft: text,
      review: "Reviewed by Ollama"
    }

  }

  // -----------------------------
  // STEP 3 — FINAL SYNTHESIZER
  // -----------------------------

  async finalSynthesizerAgent(
    query: string,
    draft: string,
    review: string,
    perspective: any
  ): Promise<{
    content: string
  }> {

    const prompt = `
Perspective:
${JSON.stringify(perspective)}

Research Question:
${query}

Draft Report:
${draft}

Reviewer Notes:
${review}

Generate the final answer.
`

    const text = await this.generate(prompt)

    return {
      content: text
    }

  }

}